password-recovery:
  code-ttl: 3m           # 3분 (단위 지원: ms, s, m, h ... 혹은 ISO-8601 'PT3M')
  resend-cooldown: 60s   # 60초
  max-attempts: 5
  temp-pw-length: 10

spring:
  security:
    oauth2:
      client:
        registration:
#          구글 로그인
          google:
            client-id: 361804552914-8um7u0bkk99nr0m6jkmes7o189cr7o7q.apps.googleusercontent.com
            client-secret: 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
            scope: [openid, profile, email]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

#          네이버 로그인 custom provider 필요
          naver:
            client-id: 1Wp9bzywroz8W3Uj0CaH
            client-secret: IzQ7uyuInu
            client-name: Naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [name, email, profile_image]

#          카카오 로그인 custom provider 필요
          kakao:
            client-id: 906ccf1dd3817e271d9f00ef65423f45
            client-secret: Ayc34KeTEe2HDu2BGO3yQgbXzrYQbaTR
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [profile_nickname, profile_image]

        provider:
#          네이버 API 엔드포인트
#          네이버는 응답이 { resultcode, message, response:{ id, ... } } 구조라
#          이후에 사용자 매핑 시 'response'에서 id 추출 로직이 필요할 수 있음
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

#          카카오 API 엔드포인트
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#          구글 API 엔드포인트
          google:
            user-name-attribute: sub

#       메일 SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: zmfpdltus012@gmail.com
    password: bluy tgxv azky wykf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.transport.protocol: smtp

app:
  mail:
    from: geulbut@gmail.com
    from-name: 글벗
